name: Trigger Databricks DLT Pipeline

on:
  workflow_dispatch:

jobs:
  run-dlt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | bash
          databricks version

      - name: Start DLT Pipeline (CLI v1.x)
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks pipelines start-update "${{ secrets.DLT_PIPELINE_ID }}"
      - name: Wait for DLT Pipeline to Finish
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          PIPELINE_ID="${{ secrets.DLT_PIPELINE_ID }}"
          UPDATE_ID=$(databricks pipelines start-update "$PIPELINE_ID" --output json | jq -r '.update_id')
          echo "Started Update ID: $UPDATE_ID"

          STATUS="RUNNING"
          while [ "$STATUS" == "RUNNING" ] || [ "$STATUS" == "PENDING" ]; do
            sleep 60
            STATUS=$(databricks pipelines get-update "$PIPELINE_ID" "$UPDATE_ID" --output json | jq -r '.update.state')
            echo "Current status: $STATUS"
          done

          if [ "$STATUS" != "COMPLETED" ]; then
            echo "Pipeline failed with status: $STATUS"
            exit 1
          fi
