name: Trigger Databricks DLT Pipeline

on:
  workflow_dispatch:

jobs:
  run-dlt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | bash
          databricks version

      - name: Start DLT Pipeline
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks pipelines start --pipeline-id "${{ secrets.DLT_PIPELINE_ID }}"
